name: Python Deploy

on:
  push:
    branches:
      - main  # Deploy on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (optional)
      # - name: Run tests
      #   run: |
      #     pytest tests/

      # Step 5: Deploy the application
      - name: Deploy to Server
        env:  # Set environment variables
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Transfer files to the server
          rsync -avz --exclude '__pycache__' . $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
          # Restart the service (example for systemd)
          ssh $DEPLOY_USER@$DEPLOY_HOST "sudo systemctl restart my-python-app"
