name: Security Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pylint
        pip install -r requirements.txt
        
    - name: Run Bandit
      run: bandit -r . -c bandit.yaml -f json -o bandit-results.json
      
    - name: Run Safety Check
      run: safety check
      
    - name: Run Pylint Security Checks
      run: pylint --disable=all --enable=security --output-format=json app.py > pylint-results.json

    - name: Upload Security Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: bandit-results.json
